services:
  web-wol:
    build: .
    image: web-wol-image
    ports:
      - "5000:5000"
      - "9:9/udp"
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - TZ=UTC
      - NETWORK_RANGE=192.168.1.0/24
    container_name: web-wol-app
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
